### PR TITLE
Adding support for WP-CLI command

### PR DESCRIPTION
**Pull request by fjarrett**
Implements #499 

I'd like to get this out in it's most basic form first, and improve on it later down the line.

The scope of this PR does not address `tail` or `export` args which could certainly be added in the future.

Right now there is only a `query` subcommand and it will accept any associative argument(s) that the `WP_Stream_Query::instance()->query()` method accepts. You can add as many of these as you'd like in parallel.

**Some examples:**

```
wp stream query
wp stream query --author=1
wp stream query --author=1 --records_per_page=20
wp stream query --author=1 --action=login --date_before=2015-01-15 --order=asc
wp stream query --author_role__not_in=administrator,editor
```

If you don't like the output format you could also specify which fields you want to output to the console using the `--fields` arg, adding multiple fields in a comma separated list.

**Some examples:**

```
wp stream query --author=1 --fields=summary
wp stream query --author=1 --fields=created,ip,summary
wp stream query --author_role=editor --date_before=2015-01-01T12:00:00 --fields=created,context,action,summary
```

The fields for default output are also filterable, so you can do:

```php
add_filter( 'wp_stream_wp_cli_default_fields', function() {
	return array( 'created', 'author_meta.display_name', 'context', 'action' );
});
```

**Update 2015-01-16**

I have added two new subcommands that accept no arguments: `wp stream account` and `wp stream help`

### CODE REVIEW

**Comment by fjarrett** [comment]
@westonruter since you were the OP for this feature, mind giving it a go?

**Comment by westonruter** [comment]
Love to, but I'm not going to have time in the foreseeable future.

**Comment by fjarrett** [comment]
@westonruter No worries, thanks man!

**Comment by fjarrett** [comment]
The scope of this PR does not address `tail` or `export` args which could certainly be added in the future.

**Comment by fjarrett** [comment]
I decided to remove the `account` and `help` subcommands for now to keep with my original goal of keeping this feature simple to start and expanding on it later.

I think the `query` subcommand and already robust enough for people to benefit from.

**Comment by fjarrett** [comment]
I've created a [Query Reference](https://github.com/wp-stream/stream/wiki/Query-Reference) in our Wiki that can be used as a reference when using this new WP-CLI command.

**Pull request merged**
